### ISSUE TITLE
Boilerplate v4.x app via Atlas

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#1]

**Comment by steveoh** [comment]
you might want to steal a little from parole or we should update atlas to use hooks and what not

**Comment by stdavis** [comment]
I agree we need to update Atlas and perhaps move some components to their own repos. Still not sure about the reducer functions. Maybe I'm too dumb for them but they seem kludgey.

**Comment by steveoh** [comment]
Yes, do we mono repo the components? 

If you can find a pattern that you like better than reducers, I will be happy to check it out.
