### ISSUE TITLE
Add Tagline

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#25]
Waiting on the text for it.

**Comment by stdavis** [comment]
@msilski - Just wanted to ping you on this issue to remind you that we are waiting on text for a tag line.

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/67306459-38751a80-f4b4-11e9-9ea5-8740e40c50cb.png)

**Comment by stdavis** [comment]
I made this completely configurable. Tag line text is in `config.json:tagLine` and the link is in `config.json:links.tagLine`.

`config.json:links.tagLine = ""` (not clickable)
![image](https://user-images.githubusercontent.com/1326248/67307726-2bf1c180-f4b6-11e9-87ed-73b757fb599e.png)


`config.json:links.tagLine = "https://test.com"` (clickable)
![image](https://user-images.githubusercontent.com/1326248/67307803-4fb50780-f4b6-11e9-8279-0e12d68c2405.png)

**Comment by msilski** [comment]
Thanks for the configurable tagline. Could you add a little bit of horizontal spacing between the title and tagline? Would it also be possible to italicize it - we'd like to see how that looks.

And Bert and I noticed that on small mobile/small screens, the tagline begins to disappear under the four-circle mini logo. Would it be possible to remove the tagline at small screens, force it to the next line, or whichever solution would be easiest for you? Thanks.

**Comment by stdavis** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/1326248/67503781-7a819600-f645-11e9-8a4d-1880eeb20cd7.png)

```css
margin-left: 5px;
font-style: italic;
```

Nice catch on the smaller screens. I'll fix that.

**Comment by msilski** [comment]
That looks great. Let's go with that.

**Comment by msilski** [comment]
Sorry - Bert has a minor change on this one. He would like to align the base of the tagline with the base of the title, and slightly increase the font, like this:

![Tagline edit](https://user-images.githubusercontent.com/1699870/67510127-9ee36f80-f651-11e9-8675-f8a2e2db480b.png)

Of course, this change adds an extra space between the tabs and the map. Either moving the tabs down or the map up would be fine. Can you make this CSS adjustment for the revised tagline?

**Comment by msilski** [comment]
Excellent. Looks great, and thanks for making the corresponding adjustment to the tabs/map.
