### ISSUE TITLE
Add a link back to the landing page

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#30]
Add link to logo/image and make sure that it work on mobile

**Comment by stdavis** [comment]
@msilski: I assume that you want the link to go to: https://wfrc.org/vision-plans/wasatch-choice-2050/ ?

**Comment by msilski** [comment]
Yes, that's correct.

**Comment by stdavis** [comment]
Is this OK for mobile?
![image](https://user-images.githubusercontent.com/1326248/66770985-2cff6f00-ee76-11e9-924d-6136746d4efd.png)

**Comment by msilski** [comment]
Let me check with Bert ...

**Comment by msilski** [comment]
I talked with Bert. Even for mobile viewing, it would be nice to have the link be visible on page load. How easy/difficult would it be to place a clickable mini logo to the left of the title (for mobile viewing only)? Here is the mini logo we would like to use:

![WC2050LogoForWeb-stackedicons](https://user-images.githubusercontent.com/1699870/66781171-d6069380-ee8f-11e9-88e2-bc981eac52a0.jpg)

If it would be difficult or prohibitive to do this, the layout shown in your screenshot would work fine.

**Comment by stdavis** [comment]
I can give that a try...

**Comment by stdavis** [comment]
How does this look?
![image](https://user-images.githubusercontent.com/1326248/66867779-3e6d7780-ef59-11e9-9b26-8dfcadbfd49a.png)

**Comment by msilski** [comment]
I will check with Bert, but it looks great to me.

**Comment by stdavis** [comment]
Does the resolution not look right? The size is about as large it can be.

**Comment by nathankota** [comment]
Looks a bit fuzzy when zoomed-in 

![image](https://user-images.githubusercontent.com/15659642/66959121-f61c8b00-f026-11e9-84f2-ddedb081909d.png)

**Comment by msilski** [comment]
When zoomed in (ex. 150%), both the full logo on desktop and mini logo on mobile do look a little fuzzy. Since I don't think we have a logo with finer resolution, let's just stick with the image as-is.
