### ISSUE TITLE
Custom Legend for Economic Clusters

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#32]
Bert to get us custom image showing point symbol classifications.

**Comment by stdavis** [comment]
@msilski: Is this still something that you want? I noticed that the production legend looks pretty good:
![image](https://user-images.githubusercontent.com/1326248/66769293-fe7f9500-ee71-11e9-9c8a-1ffa55b2904a.png)

I'm happy to give you the option of defining a URL to an image of a custom legend, I just didn't want to waste time if it wasn't needed anymore.

**Comment by msilski** [comment]
We would still like to have a custom legend for this dataset. The desired symbol/legend is the current symbology, which is a temporary configuration. Once the custom legend is in place, I will modify the symbol sizes in the dataset to reflect varying employer size.

**Comment by msilski** [comment]
It looks like this one was not included in the 1.4.0-0 pre-release. When this is ready, will I need two images - one for the swatches and one for the expanded rollover image? Or would we need to manually display the swatches by rgb/hex (like in the RTP map) with a custom expanded rollover image? I would prefer the second option, if convenient.

**Comment by stdavis** [comment]
Yes, it should have been included. I can see it on test:
![image](https://user-images.githubusercontent.com/1326248/67027039-1fd8bf00-f0c6-11e9-9568-415eb860a4e3.png)

I added a config option for defining a filename that you put in the root folder of the app that shows up in the popup. Test just has a random placeholder image for now.

I wasn't aware that you wanted two images, one for the popup and one as the thumbnail. I like the idea of manually specifying the colors via `staticColors`. I can tweak the code to allow that...

**Comment by msilski** [comment]
Sounds good to me.

**Comment by stdavis** [comment]
Here's what it will look like in the next release:
![image](https://user-images.githubusercontent.com/1326248/67225608-c8ea2700-f3f0-11e9-86dd-b6c635953b2c.png)
![image](https://user-images.githubusercontent.com/1326248/67225614-cab3ea80-f3f0-11e9-961d-ff38c6074156.png)

**Comment by msilski** [comment]
Perfect! Can you add two more color config placeholders to make six in total?

**Comment by stdavis** [comment]
You may add as many color values as you want. There's no limit. That's just an example.

**Comment by msilski** [comment]
Great. Looks good to me.

**Comment by msilski** [comment]
This should work well for us. I created a custom legend graphic and added semi-transparent color values to match, like this:

![EconomicClustersLegend_screenshot](https://user-images.githubusercontent.com/1699870/67435093-a864cd00-f5a8-11e9-9e85-cc8e3d53fe12.png)

Once this is live, in AGOL, I'll edit the symbology to vary by employer size. The static swatches and legend graphic will come in handy then.
