### ISSUE TITLE
ProjectInfo - Add support for map image layers

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#35]
- [x] research if this is even feasible and how much time it will take

**Comment by msilski** [comment]
Thanks for configuring this for map image layers - looks great. Out of curiosity, did it take a lot of work to implement? It looks like you figured this out pretty quickly.

**Comment by stdavis** [comment]
I haven't actually implemented this yet. Is it working for map image layers? If so, I would be very surprized.

**Comment by msilski** [comment]
Interesting. Information populates for the two map image layers (Economic Clusters & CDAs and RDAs) in the Economic Development tab as well as the two map image layers (Golf Courses & Green Infrastructure) in the Recreation tab.

![Map Image Services 1](https://user-images.githubusercontent.com/1699870/67509392-1dd7a880-f650-11e9-8eaa-6b3f71515c38.PNG)

![Map Image Services 2](https://user-images.githubusercontent.com/1699870/67509397-216b2f80-f650-11e9-94c7-5d12365fe66d.PNG)

**Comment by msilski** [comment]
However, information does not populate for the grouped map image layers in the Vision tab (when "useDefaultAGOLPopup": false, enabling the ProjectInfo window).

**Comment by stdavis** [comment]
Looking at this now...

**Comment by msilski** [comment]
This now works for layers in the Vision tab. Thanks!
