### ISSUE TITLE
Make ProjectInfo and Filter Widgets have a matching width

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#36]

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/67226774-0059d300-f3f3-11e9-9c22-320160fe9ddf.png)

**Comment by msilski** [comment]
It is nice to have these widgets be a fixed width - thanks!

The long layer names under the Jobs and Households datasets in the Land Use tabs make it difficult to shrink the width, which would be ideal. For now, let's leave the width as-is, but Bert and I have a modification to #31 that might allow us to shrink the width from 400px to something like 323px (323px + 7px for margin = 330px, which would equal the width of the left side panel) ...
