### ISSUE TITLE
Sidebar button is out of view on smaller screens

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#37]
From @msilski:
> For small screen sizes (ex. 340 x 650), once the left-side panel is expanded, it can't be closed because the blue button to expand/contract the panel is out of view. This could be a somewhat obscure use case (only my phone?), so I'm not 100% sure it's worth fixing. Perhaps the blue expand/contract button could be moved to inside the left-side panel for mobile? Not sure.

**Comment by msilski** [comment]
Looks great. Adding the X to the top right of the information panel was a great solution to this issue.
