### ISSUE TITLE
Build UI for adding/removing/reordering tabs

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#45]

**Comment by stdavis** [comment]
This was a helpful article: https://medium.com/tripaneer-techblog/improving-the-usability-of-multi-selecting-from-a-long-list-63e1a67aab35

This component looks the closest to what we want: https://github.com/jakezatecky/react-dual-listbox

**Comment by bertgranberg** [comment]
Could the left side label be 'Other Available Maps:' and the right side be 'Maps Displayed (max=x):' where the Maps Displayed and the map listed underneath are in bold text.

**Comment by bertgranberg** [comment]
suggest title for the multiselect panel to be "Configure Map Tabs"

**Comment by stdavis** [comment]
I have this text updated. Thanks for the feedback.

Also, just wanted you to know that we have the option to group items within the list boxes if we start getting a large number of them:
![image](https://user-images.githubusercontent.com/1326248/88840816-4883fe00-d19a-11ea-861c-ccaabe617d3e.png)
