### ISSUE TITLE
'Available' used inconsistently

### ISSUE THREAD

**Issue by bert-granberg** [agrc/wfrc#54]
in the multiselect UI control 'Available' indicated the maps that are _sitting on the bench_ waiting for the coach to put them into the game...in the URL, availableTabIDS= is the parameter for what is 'in the game' and displayed on the 'ledge'

could we change the parameter name from availableTabIDS= to mapList= and currentTabID= to selectedMap=

**Comment by stdavis** [comment]
That's a great catch. I've made these changes and they'll be part of the next release.
