### ISSUE TITLE
Add the ability to categorize maps

### ISSUE THREAD

**Issue by nathankota** [agrc/wfrc#58]
Add categories to dual list box component to handle and organize larger list of maps. 
https://github.com/jakezatecky/react-dual-listbox

![image](https://user-images.githubusercontent.com/15659642/90527796-2e04cb00-e12f-11ea-9185-1833d0c9cd8f.png)

**Comment by stdavis** [comment]
This is an all-or-nothing feature. Do we want to wait to see if we get enough maps to justify it? It a fairly trivial feature to implement. It would add a new required property to the map info config, `category`.

**Comment by nathankota** [comment]
I agree to wait and see, keep it in the backlog to know it's available.

**Comment by nathankota** [comment]
Categories:
Vision
Transportation
Land Use
Economic Development
Accessibility
Other
