### ISSUE TITLE
Add ability of drag and drop to reorder tabs

### ISSUE THREAD

**Issue by nathankota** [agrc/wfrc#59]
Allow user to click and drag map tabs in UI to reorder them. (Keep ability to reorder in the map listbox component)

![image](https://user-images.githubusercontent.com/15659642/90529225-b768cd00-e130-11ea-9246-daae62c685d9.png)

**Comment by msilski** [comment]
Awesome feature! I like how the user cannot drag the tabs outside of the header. Looks good to me.
