### ISSUE TITLE
Wire tabs up to switch map layers state

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#6]
@msilski Can you get me a spreadsheet or something that details what layers in the map correspond to what tabs? Or perhaps it would be easier to maintain separate web maps for each tab?

**Comment by msilski** [comment]
Bert and I had envisioned using separate web maps for each tab. We have not yet set up web maps with the appropriate layers for each tab, but I'm hoping to have draft web maps up and running sometime this week.  I'll let you know when I have them ready and I'll share them with you.
