### ISSUE TITLE
Query Filter Widget

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#65]
[Mock up](https://docs.google.com/presentation/d/1mZj6idDXiFdOpXer_8P52t32swD1y1QUhaUvzj-ExI0/edit?ts=5f5121d4#slide=id.p)

Toggling checkboxes would adjust the definition query on a single layer. [Here are the details](https://docs.google.com/spreadsheets/d/1BFA3-PcDI07CYR7JloeXjB78NNtnTDieRBY-ELnzsjI/edit#gid=1301409536)

I'm not yet sure if this should be done within the existing Filter widget framework or if it should be a custom component (see #47).

@nathankota Do you have any other requirements that you can remember to add to this issue?

**Comment by nathankota** [comment]
The following are from my notes, but we'll want to confirm w/WFRC. I am not able to @mention Matthew and Bert.

**Filter sections open by default:**
`Funding Program`
`Year` 
(or just `Funding Program`?)

**Filter sections closed by default:**
`Status`
`Type`

This layout would allow check boxes to be distributed vertically, if desired.

**Comment by stdavis** [comment]
I don't think that we will be able to make this work with the current filter widget. I'm planning on implementing this as a configurable, generic "QueryFilter" widget so that it could be used in other maps as well. I don't feel like it's very specific to the TIP Projects map.

**Comment by stdavis** [comment]
@msilski Does this look like a reasonable configuration for the QueryFilter widget? Would it allow you enough flexibility?

https://gist.github.com/stdavis/1caaaed863b6be79ca7ecf6a8c200f98

**Comment by msilski** [comment]
@stdavis That looks good to me. Just to clarify - for a checkbox, is the _"other" = true_ line used in place of _"values"_ to group all other values?

**Comment by stdavis** [comment]
> Just to clarify - for a checkbox, is the _"other" = true_ line used in place of _"values"_ to group all other values?

Yes, that's my thought. 

Let me know if you can think of any other issues. I'm going to start coding it today. Thanks for the review!

**Comment by nathankota** [comment]
**WFRC Feedback:**

- Force scrollbar on macOS

- Specify title in query pane (e.g. replace _Query Filter_ with _TIP Project Filter_)

- Enable vertical folding of query sections. _Funding Program_ open by default, all the rest closed.

- Horizontal wrapping of text not ideal. 
    - Can one item per line be specified?
    - Can the values be put in columns or a matrix to distribute them more evenly?
