### ISSUE TITLE
Replace Logo

### ISSUE THREAD

**Issue by nathankota** [agrc/wfrc#71]
> Replace Wasatch Choice 2050 logo in top right corner with Wasatch Choice Vision logo (see attached). High priority.

`Wasatch_Choice_Logo_Color.png` found [here](https://drive.google.com/drive/u/0/folders/1zwEmc9pz5FDueEOZBNiBQgEVG-jR1V5_)

**Comment by msilski** [comment]
Thanks for updating the logo. Do we need to provide a higher-resolution image to match that of the old Wasatch Choice 2050 logo?

![image](https://user-images.githubusercontent.com/1699870/97635897-c6f07600-19fd-11eb-9827-4aa07dab9bad.png)

![image](https://user-images.githubusercontent.com/1699870/97635933-d4a5fb80-19fd-11eb-8678-6bfd09f3a015.png)

**Comment by stdavis** [comment]
@msilski: I didn't notice the resolution difference on my HD display but I can see it on my other display now. Nice catch. I'm having struggles resizing the .png. Do you have an SVG version available that you can send me?

**Comment by msilski** [comment]
After trying to find a better resolution logo, the Wasatch Choice Vision logo I e-mailed on Oct. 26 (approx. 69KB) is still the best available version.

I did some digging and found the source file for the image in the app in _static < media < logo.b87ff9ae.png_, whose file size is around 22KB or 176x70. As a hack, I replaced this png with the approx. 69KB or 2142x864 version, giving it the same name of _logo.b87ff9ae.png_. Here's what it looks like:

**OLD:**
![image](https://user-images.githubusercontent.com/1699870/98182361-cdca2d80-1ec2-11eb-9735-b100ee1c5e30.png)

**NEW:**
![image](https://user-images.githubusercontent.com/1699870/98182388-db7fb300-1ec2-11eb-9134-61b748f27ae8.png)

There's a slight improvement - I think it's passably better. My approach is probably not the right way or optimized way to use the sharper logo, though. Let me know if there's a better way to do this - overwriting the 22KB image with the raw 69KB image.

**Comment by stdavis** [comment]
That just seems like a waste to ship a much larger image. But perhaps the software that I used to shrink it in the first place didn't do a great job of resampling? I do think that if you could find a vector version of the logo, that would allow us to either serve it up directly or do a better job of resampling. If that's not available, would you like me to just use the original 69KB image for now?

**Comment by msilski** [comment]
Right. Our communications specialist (who sent me the image) is not very technical - I'm not sure she would know what an SVG is. So let's use the original 69KB image for now.

**Comment by msilski** [comment]
This looks good and is in production. You can close the issue if you like.
