### ISSUE TITLE
Disable Tabs Limitation

### ISSUE THREAD

**Issue by nathankota** [agrc/wfrc#73]
For map ledge:

> We've received feedback that users might want to have many tabs available and that the max tab # is artificial. If possible, we'd like to see a default tab configuration (Vision, Transportation, Land Use, Economic Development) on map load with the ability for users to add as many tabs as desired. Medium priority.

**Comment by msilski** [comment]
The new About scrollbar looks good on desktop and mobile. It also makes a little more room for the About content, which is nice.

On mobile, with several tabs available, the ability to drag and drop tabs competes with scrolling horizontally to view tabs. I found myself accidentally reordering tabs. Having both functionalities available works okay. Maybe it's worth considering if drag and drop should be disabled on mobile? I'm not sure.

![Screenshot_20201029-160000](https://user-images.githubusercontent.com/1699870/97637807-edfc7700-1a00-11eb-9acb-28ba1f8d6f91.png)

**Comment by stdavis** [comment]
I like the idea of disabling the drag and drop on mobile. I had the same issue of struggling to scroll on mobile. I'll give it a try and push a new version.

**Comment by stdavis** [comment]
I pushed a new version (v4.0.0-1) to test that disables drag and drop for mobile devices. Let me know what you think.

**Comment by msilski** [comment]
Looks great to me. Probably the right call to disable drag and drop for mobile.
