### ISSUE TITLE
Empty values in project info results

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#75]
From @msilski:
>Only pop-ups for Bike/Ped display attribute information. All other layers (Centers, Light Rail, etc.) show the fields but not the attributes. What's strange is that they display just fine in the AGOL web map. It could be related to my use of reserved words like "Name" and "Type," but I'm not sure.
>![image](https://user-images.githubusercontent.com/1326248/98050288-9722e300-1dee-11eb-999b-5b9311d70f5e.png)

My response:
>I've begun to dig into these bugs and I've found at least one issue related to map services hosted on https://gis.wfrc.org/arcgis/rest/services. When they are loaded as map image layers in the map, I hit the identify endpoint for the service. The issue that I'm seeing is that the services hosted on your server are returning features using field aliases rather than the field names themselves. This results in a mismatch with the popup template and thus empty values in the project information table. There is a parameter called `returnFieldName` that I'm passing that causes the data to be returned using field names (not aliases) but that parameter was introduced at 10.5 and I can see that you are running 10.4.1. 😬 Totally my bad for missing this.

>There are a few options that I can see to move forward. One is that I write a translation function that takes graphics with field aliases and translates them to graphics with the base field names. This is definitely doable. I think that it would take a few hours to implement and it's a bit of a hack but I think nothing crazy.

>The other option is to upgrade your server to at least 10.5. Upgrading our instance of ArcGIS Server at AGRC takes months and is a major pain. I'm not sure what the pain level is for you. Perhaps you were looking for an excuse to upgrade already? If so, it may be best to just wait for the upgrade.

And @msilski:
>Thanks for looking into these. We have been looking at upgrading our server version this year to at least 10.7 - perhaps this would force the issue and speed up the timeline for that one. I've been trying to fit the server upgrade into my schedule for most of the year. That would be my ideal solution. I think resolving this pop-up issue can wait until we upgrade the server.

Just wanting to get this recorded. I'll keep this issue open until the upgrade happens. If you change your mind and would like me to code around this, just let me know.

**Comment by msilski** [comment]
I talked with Bert about this issue and he would like to move this forward. Could you apply the possible fix you mentioned (or something similar) to get around our server issue?

**Comment by stdavis** [comment]
Hey @msilski: I've pushed a new update (v4.0.1-0) to the [test site](https://test.mapserv.utah.gov/wfrc/) that contains the workaround that I proposed above. Give it a look and tell me what you think.

**Comment by msilski** [comment]
Wow! It looks great. The attributes in the Vision tab pop-up appear as expected.

I really appreciate this fix. You got to it way, way, way faster than we would have with the GIS server upgrade.

**Comment by stdavis** [comment]
Here's the production release with the fix in it: https://github.com/agrc/wfrc/releases/tag/v4.0.1

**Comment by msilski** [comment]
Thanks! I tested it locally and deployed the release.

**Comment by stdavis** [comment]
Looks like WFRC has updated their server. This work-around could be removed. Reopening...

**Comment by msilski** [comment]
Yes - we updated our server at the end of last year. After the server upgrade, I discovered that the fix in 4.0.1 no longer worked/was no longer needed in our [map](https://wfrc.org/wasatch-choice-map), so I rolled back to 4.0.0. In this prerelease, it looks like the pop-up issue is back, though.

**Comment by stdavis** [comment]
I've reverted this work-around for the next release.
