### ISSUE TITLE
Reset Project Information window scroll on map click

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#76]
From @msilski:
>(1) When a user clicks on a map feature, selects that feature in the Project Information window, and scrolls down in the pop-up, when they click on another map feature, the Project Information window does not reset to the top. Can you reset the window to the top each time the user clicks on a map feature?

>First click: pop-up has been scrolled down
![image](https://user-images.githubusercontent.com/1326248/108775999-09930c80-751f-11eb-8e8e-916469cf7225.png)

>Second click: pop-up remains scrolled-down
![image](https://user-images.githubusercontent.com/1326248/108776009-0e57c080-751f-11eb-87bb-1e3145a79edc.png)

**Comment by msilski** [comment]
This works great. Hope it wasn't too difficult to implement.

This may or may not be related to the change, but I noticed that the map and its tools initially load a few pixels higher (as seen below), then drops down to its normal position. I don't think it's a deal-breaker, and it might be the trade-off with the fresh reset of the pop-up. Either way, could you look into why the map is loading this way? Thanks.

![image](https://user-images.githubusercontent.com/1699870/108890807-3f8dca80-75cb-11eb-83d9-ec40f1b6c927.png)

**Comment by stdavis** [comment]
Nice catch! I didn't notice that when the site loaded on my local machine. I think that I have it fixed.
