### ISSUE TITLE
Layer Selector: replace three overlays with a singles overlay for cities

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#77]
From @msilski:
>The Layer Selector widget currently contains three overlays. In place of the three overlays, can you configure the widget to allow for a cities overlay? I've done this in our RTP map using a GIS service to draw the cities. You can use that same service to toggle the Cities overlay in the Wasatch Choice Map. I imagine it would look something like this:
![image](https://user-images.githubusercontent.com/1326248/108776797-19f7b700-7520-11eb-87d7-fa38842d5bf8.png)

**Comment by msilski** [comment]
I should have originally tried to make this change straight in the config - oops.

I noticed that when the Cities layer is turned on, after a click event, that layer's pop-up information is added to the Project Information window.
![image](https://user-images.githubusercontent.com/1699870/108890265-98a92e80-75ca-11eb-9744-769901bd9a01.png)
If possible, I would like this layer's info to not display in the window. What would be the best way to disable that? Is there a setting to disable the default pop-up (ex. Layer Name: {NAME})? As a workaround, I could convert that data from polygons to lines - then a user would only see the pop-up info when they click on the boundary.

**Comment by stdavis** [comment]
I added a new config to solve this problem:
![image](https://user-images.githubusercontent.com/1326248/109056768-1be78480-769e-11eb-9aed-c3267c10a7fe.png)
