### ISSUE TITLE
Port ProjectInfo widget from WAB

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc#8]
No need for comments in this app.

Look into pulling the popup contents as defined in the web map layer.

**Comment by stdavis** [comment]
First get it working for feature layers. Then see what it will take to make it work with map image layers.

**Comment by stdavis** [comment]
This widget has been ported "as is" from the WAB project. It works with feature layers only. Let's create new issues for enhancements to it.

**Comment by stdavis** [comment]
I'd love any feedback that you have on it currently.

**Comment by msilski** [comment]
Thanks for your work on this one. It looks just about ready to go. We will still use the default AGOL popups for now. I noticed that when AGOL popups are switched to true, it hides the Project Information widget - nice.

Will the final Project Information widget use the AGOL-configured popups? If not, I'll need to clean up several datasets before the widget goes live.

It looks like the plan is still to try to have this widget work with map image layers. If it would be too time-consuming or difficult, we can probably copy over some of the live layers we've been using so they can be feature services - probably not a big deal.

Also, I noticed the widget changes in size depending on the attribute size. Would it be possible to constrain it to the same width as the Layers widget?

**Comment by stdavis** [comment]
> Will the final Project Information widget use the AGOL-configured popups? If not, I'll need to clean up several datasets before the widget goes live.

https://github.com/agrc/wfrc/issues/34

> It looks like the plan is still to try to have this widget work with map image layers. If it would be too time-consuming or difficult, we can probably copy over some of the live layers we've been using so they can be feature services - probably not a big deal.

https://github.com/agrc/wfrc/issues/35

I'll look into this and see if it's feasible. I think that I should be able to get it to work. I don't believe that adding duplicate feature services to the web map would help this issue.

> Also, I noticed the widget changes in size depending on the attribute size. Would it be possible to constrain it to the same width as the Layers widget?

https://github.com/agrc/wfrc/issues/36

I'm going to close this issue in favor of the newly added issues. Please let me know if I failed to capture any feedback in the new issues.

**Comment by msilski** [comment]
The newly added issues look great. Thanks for taking a look at those.
